/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:640e4946-fbe4-4462-bdef-5d42dede2d20",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_3BNbuJy6I",
    "aws_user_pools_web_client_id": "12nhb6c93tjflq5o9j3l50pdbr",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "API": {
        "GraphQL": {
            "endpoint": "https://od2emqnygba2daocqe2grilgju.appsync-api.us-east-2.amazonaws.com/graphql",
            "region": "us-east-2",
            "defaultAuthMode": "apiKey",
            "apiKey": "da2-6zjhsowuezda3m7rhnos326bia"
        }
    }
};


export default awsmobile;
